<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HRAttendanceMVC.Application\HRAttendanceMVC.Application.csproj" />
		<ProjectReference Include="..\HRAttendanceMVC.Infrastructure\HRAttendanceMVC.Infrastructure.csproj" />
		<ProjectReference Include="..\HRAttendanceMVC.Domain\HRAttendanceMVC.Domain.csproj" />
	</ItemGroup>

</Project>
